# -*- coding: utf-8 -*-
"""Assignment01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14J_UH_WUzdGUfq2Le_mhAWMyeAl34MQV
"""

#Question 2
def Sal(work_hours):
  a = 0
  for x in work_hours:
    if x[-1] == 'F':
      if(a < x[-2]):
        a = x[-2]
        nam = x[-3] 
  return nam,a*20

work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]


name,sal=Sal(work_hours)
print("the female worker that worked the most hours is",name,"and she should be paid",sal)



#question 3
import numpy as np

arr=  [[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]]

arr = np.vstack(arr)
print(arr)
print()
id = np.eye(5)
print(id)
print()
print(arr@id)
print()
print(arr.shape)
print()
print(np.size(arr))

#Question 3
import matplotlib.pyplot as plt

from google.colab import drive

drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

file_name = "shin.jpg"  


image = mpimg.imread(file_name)
   


plt.imshow(image)
plt.axis('on')
plt.show()



#Question01
def R_A(a,b):
   return a[::-1]+b
R_A("yes","right")

#Question 01
#list
ls1=[0,1,2]
ls2=[3,4,5]
ls1.extend(ls2) #extending the list
print(ls1)
ls2.pop(-2)    #removing the second element from the end
print(ls2)
ls1.append(5)  #adding an element at the end
print(ls1)

#tuple
t1=(2,3,4)
t2=(5,4,3,4,3)
t3=t1+t2   #concatenate
print(t3)
print(len(t3)) #length of the tuple
print(sorted(t3))  #sorting elements

#sets
s={22,33,22}
s2={1,2}
s.add(8)  #adding an element
print(s)
s.union(s2) #elements from both sets
print(s)
s.remove(8) #removing an element
print(s)

#dictionary
d1={1:"s",2:"r",3:"i"}
d1.keys() #returns all the keys of dic
d1.values()  #returns all the values of dic
d1.clear()  #clears all the elements